# Numpy lec 1


In [1]:
L=[1,2,3,4,5,6]*2

In [2]:
L

[1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6]

Installing Numpy

In [3]:
!pip install numpy

Importing numpy Library

In [4]:
import numpy as np

In [5]:
L

[1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6]

To convert into array use np.array

In [6]:
a=np.array(L)

In [7]:
a

array([1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6])

Check type

In [8]:
type(a)

numpy.ndarray

Check dimension use

In [9]:
a.ndim

1

In [10]:
a.shape

(12,)

In [16]:
a1=np.array([[1,2,3],
             [4,5,6]])

In [17]:
a1.ndim

2

In [18]:
a1.shape

(2, 3)

In [19]:
type(a1)

numpy.ndarray

In [20]:
a2=np.array([[[1,2,3],
             [4,5,6],
              [7,8,9]]])

In [21]:
type(a2)

numpy.ndarray

In [23]:
a2.ndim

3

In [25]:
addition=[0,0,0,0]
multiplication=[1,1,1,1]

In [27]:
a=np.ones(4)
a

array([1., 1., 1., 1.])

In [28]:
a.dtype

dtype('float64')

In [29]:
b=np.zeros(5)

In [30]:
b

array([0., 0., 0., 0., 0.])

In [31]:
a1=np.ones(5,dtype=int)

In [32]:
a1

array([1, 1, 1, 1, 1])

In [33]:
a1.dtype

dtype('int32')

In [39]:
a=np.ones((2,3),dtype=int)

In [40]:
a

array([[1, 1, 1],
       [1, 1, 1]])

In [45]:
a=np.ones((2,3,3),dtype=int)

In [46]:
a

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

In [47]:
a=np.ones(5,dtype=bool)

In [48]:
a


array([ True,  True,  True,  True,  True])

In [49]:
a=np.zeros(5,dtype=bool)

In [50]:
a

array([False, False, False, False, False])

In [52]:
a=np.array([1,2,3,4,5,6,7,8,9,10])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [53]:
a.ndim

1

In [54]:
np.arange(1,15)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [56]:
np.arange(1,200,6)

array([  1,   7,  13,  19,  25,  31,  37,  43,  49,  55,  61,  67,  73,
        79,  85,  91,  97, 103, 109, 115, 121, 127, 133, 139, 145, 151,
       157, 163, 169, 175, 181, 187, 193, 199])

In [57]:
np.linspace(1,12,18)

array([ 1.        ,  1.64705882,  2.29411765,  2.94117647,  3.58823529,
        4.23529412,  4.88235294,  5.52941176,  6.17647059,  6.82352941,
        7.47058824,  8.11764706,  8.76470588,  9.41176471, 10.05882353,
       10.70588235, 11.35294118, 12.        ])

In [67]:
a4=np.arange(1,17)

In [68]:
a4

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [69]:
len(a4)

16

In [70]:
a4.reshape(4,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [71]:
a4.ndim

1

In [72]:
np.zeros(6,dtype=int)

array([0, 0, 0, 0, 0, 0])

In [73]:
c=np.zeros((2,3))

In [74]:
c

array([[0., 0., 0.],
       [0., 0., 0.]])

In [77]:
c=np.zeros((2,3,2),dtype=int)

In [78]:
c

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0]]])

# Numpy Lec2

In [80]:
b=np.arange(1,25).reshape(6,4)

In [81]:
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [82]:
b.ndim

2

In [87]:
b=np.arange(1,25).reshape(2,4,3)

In [88]:
b

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

In [89]:
b.ndim

3

To convert into 1D use Ravel

In [90]:
b.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [91]:
b.ravel().ndim

1

In [93]:
b.flatten(order="F")

array([ 1, 13,  4, 16,  7, 19, 10, 22,  2, 14,  5, 17,  8, 20, 11, 23,  3,
       15,  6, 18,  9, 21, 12, 24])

In [97]:
c=np.arange(1,17).reshape(4,4)

In [98]:
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [99]:
c.ndim

2

In [104]:
c.transpose()

array([[ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15],
       [ 4,  8, 12, 16]])

In [105]:
b

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [106]:
b.reshape(1,-1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24]])

In [107]:
b.reshape(-1,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [108]:
d=np.arange(1,10).reshape(3,3)

In [109]:
d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [110]:
f=np.arange(1,10).reshape(3,3)

In [111]:
f

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [112]:
np.add(d,f)

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [113]:
np.subtract(d,f)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [114]:
np.divide(d,f)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [115]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [116]:
a.min()

1

In [117]:
a.max()

16

In [127]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [128]:
a.min(axis=1)

array([ 1,  5,  9, 13])

In [129]:
a.max(axis=1)

array([ 4,  8, 12, 16])

In [130]:
a.min(axis=0)

array([1, 2, 3, 4])

In [131]:
a.max(axis=0)

array([13, 14, 15, 16])

In [132]:
a.argmax()

15

In [133]:
a.argmin()

0

In [134]:
a.argmax(axis=1)

array([3, 3, 3, 3], dtype=int64)

In [125]:
a.argmin(axis=0)

array([0, 0, 0, 0], dtype=int64)

In [126]:
np.sum(a,axis=1)

array([10, 26, 42, 58])

In [135]:
np.sum(a,axis=0)

array([28, 32, 36, 40])

In [136]:
np.trace(a)

34

In [137]:
np.mean(a)

8.5

In [138]:
np.std(a)

4.6097722286464435

In [139]:
np.var(a)

21.25

In [140]:
np.sqrt(a)

array([[1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712],
       [3.        , 3.16227766, 3.31662479, 3.46410162],
       [3.60555128, 3.74165739, 3.87298335, 4.        ]])

In [145]:
r=np.arange(1,101).reshape(10,10)

In [146]:
r

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [154]:
r[4]

array([41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [155]:
r[4:]

array([[ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [157]:
r[:4]

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40]])

In [159]:
r[4:7]

array([[41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
       [51, 52, 53, 54, 55, 56, 57, 58, 59, 60],
       [61, 62, 63, 64, 65, 66, 67, 68, 69, 70]])

In [160]:
r[2:9:2]

array([[21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
       [61, 62, 63, 64, 65, 66, 67, 68, 69, 70],
       [81, 82, 83, 84, 85, 86, 87, 88, 89, 90]])

In [162]:
r[2:4,2:8]

array([[23, 24, 25, 26, 27, 28],
       [33, 34, 35, 36, 37, 38]])

# Numpy lec 3

In [163]:
r[:,3:10:2]

array([[  4,   6,   8,  10],
       [ 14,  16,  18,  20],
       [ 24,  26,  28,  30],
       [ 34,  36,  38,  40],
       [ 44,  46,  48,  50],
       [ 54,  56,  58,  60],
       [ 64,  66,  68,  70],
       [ 74,  76,  78,  80],
       [ 84,  86,  88,  90],
       [ 94,  96,  98, 100]])

In [164]:
Y=np.arange(1,10).reshape(3,3)

In [165]:
Y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [166]:
Y1=np.arange(1,10).reshape(3,3)

In [167]:
Y1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [168]:
np.dot(Y,Y1)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [170]:
a=np.arange(1,17).reshape(4,4)
b=np.arange(17,33).reshape(4,4)

In [171]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [172]:
b

array([[17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [174]:
np.concatenate((a,b))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [175]:
np.concatenate((a,b),axis=1)

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

In [177]:
np.hstack((a,b))

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

In [178]:
np.vstack((a,b))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [179]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [180]:
np.split(a,2)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]

In [181]:
np.split(a,4)

[array([[1, 2, 3, 4]]),
 array([[5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12]]),
 array([[13, 14, 15, 16]])]

In [182]:
np.split(a,4,axis=1)

[array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]]),
 array([[ 4],
        [ 8],
        [12],
        [16]])]

In [184]:
s=np.split(a,2,axis=1)

In [185]:
s

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16]])]

In [186]:
type(s)

list

In [187]:
s[0]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]])

In [191]:
a=np.array([11,22,33,44,55,66,77,88,99])

In [192]:
a

array([11, 22, 33, 44, 55, 66, 77, 88, 99])

In [193]:
np.split(a,[2])

[array([11, 22]), array([33, 44, 55, 66, 77, 88, 99])]

In [196]:
np.split(a,[2,5])

[array([11, 22]), array([33, 44, 55]), array([66, 77, 88, 99])]

In [197]:
from random import*

In [207]:
g=np.random.random()

In [208]:
g

0.1404419655059166

In [209]:
h=np.random.random((2,3))

In [210]:
h

array([[0.9709597 , 0.02660688, 0.59154477],
       [0.04052073, 0.99250013, 0.23047645]])

In [211]:
type(h)

numpy.ndarray

In [206]:
np.random.random(5)

array([0.14319546, 0.20527528, 0.61083856, 0.61789045, 0.76512751])

In [213]:
np.random.random((2,3,4))

array([[[0.58837939, 0.45989432, 0.66296817, 0.51669186],
        [0.50777263, 0.94292385, 0.45565126, 0.33510993],
        [0.69551928, 0.05049404, 0.64165877, 0.45243105]],

       [[0.33343768, 0.44934859, 0.08455358, 0.31485726],
        [0.50405818, 0.49632725, 0.47104064, 0.14268553],
        [0.38871161, 0.46065546, 0.19555815, 0.87494286]]])

In [219]:
np.random.randint(15,45,size=(2,4))

array([[44, 37, 23, 26],
       [42, 15, 38, 28]])

In [221]:
np.random.randint(15,size=(2,4))

array([[ 7,  2,  9, 11],
       [12,  5, 10,  1]])

In [222]:
np.random.choice(a)

66

In [223]:
np.random.permutation(a)

array([77, 55, 22, 99, 88, 33, 11, 44, 66])

In [224]:
np.random.uniform(1,100,250)

array([99.80969811, 45.85321023, 66.8438059 , 29.17889322, 75.39485894,
       27.79486451, 60.06292437, 99.90213856, 35.42570522, 84.3074497 ,
       54.79192303, 41.62641798, 70.27740743, 61.29966112, 19.85022762,
       53.27832816, 32.65300709, 75.99220111, 66.6268595 , 41.11098346,
       85.68323009, 80.96602233,  3.19841411, 16.39283988, 51.28135987,
       21.05974887, 24.70021993, 74.2228825 , 26.58767484, 63.0803061 ,
       45.47581042, 99.08588336, 61.26324756, 39.38718739, 95.73554353,
       23.01875326, 69.52686599, 76.46801673, 54.88890854, 89.29459429,
       84.87627263, 70.50470321, 84.61161827, 19.77751402, 35.30809449,
       81.31884095, 67.57827578,  4.73184331, 66.70046764,  9.13132992,
       47.43251119, 71.80482146, 67.81552823, 11.66798467, 13.90532763,
       89.09271444, 63.19717284, 69.76154538, 85.62041117, 69.0639472 ,
       31.54555042,  9.10951518, 46.9248676 , 67.1813421 , 49.75962243,
       90.82696765,  2.66449351, 34.03952336, 89.49824046, 26.52

In [225]:
np.random.normal()

-0.420939223563311

In [227]:
s="python"
s1="data science"

In [228]:
np.char.add(s,s1)

array('pythondata science', dtype='<U18')

In [230]:
np.char.upper(s)

array('PYTHON', dtype='<U6')

In [231]:
np.char.lower(s1)

array('data science', dtype='<U12')

In [238]:
np.char.split(s1)

array(list(['data', 'science']), dtype=object)

In [240]:
np.char.center(s,20,"*")

array('*******python*******', dtype='<U20')

In [242]:
np.char.center(s,20," ")

array('       python       ', dtype='<U20')